data:
  dir: data/sepsis

  case_key: "Case ID"
  activity_key: Activity
  resource_key: Resource
  timestamp_key: "time:timestamp"
  label_key: label

  train_split: 0.65
  val_split: 0.15
  test_split: 0.2
  max_seq_len: 61  # train-split p99 (longest case: 185)
  condition_features:
    - case:label
  attribute_features:
    - DiagnosticArtAstrup
    - DiagnosticBlood
    - DiagnosticECG
    - DiagnosticIC
    - DiagnosticLacticAcid
    - DiagnosticLiquor
    - DiagnosticSputum
    - DiagnosticUrinaryCulture
    - DiagnosticUrinarySediment
    - DiagnosticXthorax
    - DisfuncOrg
    - Hypotensie
    - Hypoxie
    - InfectionSuspected
    - Infusion
    - Oligurie
    - SIRSCritHeartRate
    - SIRSCritLeucos
    - SIRSCritTachypnea
    - SIRSCritTemperature
    - SIRSCriteria2OrMore
    - Age
    - CRP
    - LacticAcid
    - Leucocytes
  time_clip_percentile: 99.0
  batch_size: 256
  num_workers: 4

training:
  max_num_epochs: 1250  # 508 train traces, cut into 8070 prefix/suffix pairs
